//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoList.LocalizationResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить упражнение.
        /// </summary>
        internal static string AddExercise {
            get {
                return ResourceManager.GetString("AddExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новое упражнение.
        /// </summary>
        internal static string CreationTask {
            get {
                return ResourceManager.GetString("CreationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите описание задачи.
        /// </summary>
        internal static string DescriptionMessage {
            get {
                return ResourceManager.GetString("DescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавьте вашу первую задачу.
        /// </summary>
        internal static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтягивания.
        /// </summary>
        internal static string Pullups {
            get {
                return ResourceManager.GetString("Pullups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отжимания.
        /// </summary>
        internal static string Pushups {
            get {
                return ResourceManager.GetString("Pushups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бег.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приседания.
        /// </summary>
        internal static string Squats {
            get {
                return ResourceManager.GetString("Squats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание задачи.
        /// </summary>
        internal static string TaskDefenition {
            get {
                return ResourceManager.GetString("TaskDefenition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполненные задачи:.
        /// </summary>
        internal static string TitleCompleteTasks {
            get {
                return ResourceManager.GetString("TitleCompleteTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую задачу.
        /// </summary>
        internal static string TitleCreationTask {
            get {
                return ResourceManager.GetString("TitleCreationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невыполненные задачи:.
        /// </summary>
        internal static string TitleIncompleteTasks {
            get {
                return ResourceManager.GetString("TitleIncompleteTasks", resourceCulture);
            }
        }
    }
}
